import { xdr } from '@stellar/stellar-sdk';
import { getContractSpec } from './contract-spec-registry';

/**
 * Regression guard for the write-path encoding gap flagged in
 * docs/CONTRACT_BUILD_DIAGNOSIS.md: SorobanClientService's generic
 * nativeToScVal(value) cannot represent a contract's custom Soroban
 * union/enum types (SignalAction, ProposalType, ...) from a bare JS value.
 * Confirmed directly: nativeToScVal('Buy') produces scvString, but a
 * SignalAction argument requires scvVec([scvSymbol('Buy')]) — the contract
 * would reject or misinterpret the call.
 *
 * These tests encode real write-path arguments through the actual compiled
 * contract spec (src/contracts/specs/*.spec.xdr.txt, generated by
 * scripts/generate-contract-specs.sh from the real WASM) rather than a
 * hand-written assumption about the encoding. If a contract's enum ever
 * changes shape (a variant renamed, a void variant gaining a payload, ...)
 * without the spec snapshot being regenerated, these tests still pass
 * against the stale snapshot — but buildInvocationWithSpec's use of the
 * *same* snapshot at runtime means backend and snapshot can never disagree
 * with each other, only both drift from the real contract together, and
 * scripts/generate-contract-specs.sh existing at all is what keeps that
 * regeneration a one-command, low-friction step instead of a silent gap.
 */
describe('contract-spec-registry', () => {
  it('encodes a unit-variant SignalAction as scvVec([scvSymbol(tag)]), not scvString', () => {
    const spec = getContractSpec('signal_registry');
    const scArgs = spec.funcArgsToScVals('create_signal', {
      provider: 'GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5',
      asset_pair: 'XLM/USDC',
      action: { tag: 'Buy' },
      price: 100n,
      rationale: 'test',
      expiry: 999n,
      category: { tag: 'SWING' },
      tags: [],
      risk_level: { tag: 'Low' },
    });
    const action = scArgs[2]; // create_signal's 3rd input is `action`

    expect(action.switch()).toEqual(xdr.ScValType.scvVec());
    const vec = action.vec()!;
    expect(vec).toHaveLength(1);
    expect(vec[0].switch()).toEqual(xdr.ScValType.scvSymbol());
    expect(vec[0].sym().toString()).toBe('Buy');
  });

  it('rejects a SignalCategory tag that is not a real contract variant', () => {
    const spec = getContractSpec('signal_registry');
    expect(() =>
      spec.funcArgsToScVals('create_signal', {
        provider: 'GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5',
        asset_pair: 'XLM/USDC',
        action: { tag: 'Buy' },
        price: 100n,
        rationale: 'test',
        expiry: 999n,
        // Not a real SignalCategory variant (the real ones are SCALP/SWING/
        // LONG_TERM/ARBITRAGE/PREMIUM) -- this must fail loudly rather than
        // silently encode something the contract will reject or misread.
        category: { tag: 'Spot' },
        tags: [],
        risk_level: { tag: 'Low' },
      }),
    ).toThrow();
  });

  it('encodes a tuple-variant ProposalType as scvVec([scvSymbol(tag), ...values])', () => {
    const spec = getContractSpec('governance');
    const [, proposalType] = spec.funcArgsToScVals('create_proposal', {
      proposer: 'GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5',
      proposal_type: { tag: 'SignalProposal', values: ['issue-123'] },
      title: 'Test',
      description: 'desc',
      execution_payload: Buffer.from('abc'),
      category: { tag: 'General' },
      use_quadratic_voting: false,
    });

    expect(proposalType.switch()).toEqual(xdr.ScValType.scvVec());
    const vec = proposalType.vec()!;
    expect(vec).toHaveLength(2);
    expect(vec[0].sym().toString()).toBe('SignalProposal');
    expect(vec[1].str().toString()).toBe('issue-123');
  });

  it('rejects a ProposalType call with the wrong number of associated values for the variant', () => {
    const spec = getContractSpec('governance');
    expect(() =>
      spec.funcArgsToScVals('create_proposal', {
        proposer: 'GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5',
        // ParameterChange needs 3 values (string, i128, i128); giving it
        // SignalProposal's shape must fail rather than send malformed XDR.
        proposal_type: { tag: 'ParameterChange', values: ['only-one-value'] },
        title: 'Test',
        description: 'desc',
        execution_payload: Buffer.from('abc'),
        category: { tag: 'General' },
        use_quadratic_voting: false,
      }),
    ).toThrow();
  });

  it('encodes GovernanceVoteType (cast_vote) as scvVec([scvSymbol(tag)])', () => {
    const spec = getContractSpec('governance');
    const [, , voteType] = spec.funcArgsToScVals('cast_vote', {
      proposal_id: 1,
      voter: 'GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5',
      vote_type: { tag: 'For' },
    });

    expect(voteType.switch()).toEqual(xdr.ScValType.scvVec());
    expect(voteType.vec()![0].sym().toString()).toBe('For');
  });

  it('throws a clear error for a contract package with no committed spec snapshot', () => {
    expect(() => getContractSpec('not_a_real_package')).toThrow(/generate-contract-specs\.sh/);
  });
});
